apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aadpodidentity-foodsafety
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aadpodidentity-foodsafety
        aadpodidbinding: foodsafety
    spec:
      containers:
      - name: aadpodidentity-foodsafety
        image: bobjacfoodsafety.azurecr.io/aadpodidentitydemo:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: TESTENV
          value: "aadpodidentity-foodsafety" 
---
apiVersion: v1
kind: Service
metadata:
  name: aadpodidentity-foodsafety
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: aadpodidentity-foodsafety